trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -e ".[test]"
  displayName: 'Install dependencies'

- script: |
    python -m pip freeze
  displayName: 'Package listing'

- script: |
    python -m pip install pytest pytest-azurepipelines
    pytest --cov=./ --cov-report=xml:coverage.xml --cov-report=term-missing
    curl -Os https://uploader.codecov.io/latest/linux/codecov
    chmod +x codecov
    ./codecov -t "$CODECOV"
  displayName: 'pytest'
  env:
    CODECOV: $(codecov)
