name: build

on:
  release:
    types: [ released ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      sdist: true
      targets: |
        # Linux wheels
        - cp3*-manylinux_x86_64
        # macOS Intel wheels
        - cp3*-macosx_x86_64
        # macOS arm64 wheels
        - cp3*-macosx_arm64
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
